# Docker compose Pablo Lopez 
services:

  db:
    image: mariadb:10.6
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_site
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_content:/var/www/html
      - git_content:/var/www/html/git
      
  # Contenedor auxiliar para gestionar el código desde GitHub
  git-sync:
    build:
      context: .
      dockerfile: Dockerfile.git-sync
    volumes:
      - git_content:/git-site
    environment:
      REPO_URL: https://github.com/blaaw/grass-component
    depends_on:
      - wordpress

volumes:
  db_data:
  wp_content:
  git_content:
